### PR TITLE
Use negative loglikelihood from rampwf for logloss score

### PR DESCRIPTION
**Pull request by kegl**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
All the commits here are already included in the merged #1 (I only used again sklearn's log_loss instead of rampwf, is that what you want to change?)

**Comment by kegl** [comment]
yes

**Comment by kegl** [comment]
Please fix the PR https://github.com/paris-saclay-cds/ramp-workflow/pull/154
Then maybe also add precision and recall to rampwf, they are generic.

**Comment by kegl** [comment]
Can we merge?

**Comment by jorisvandenbossche** [comment]
I added CI, it's green now

**Pull request merged**
