### PR TITLE
Expand starting kit notebook

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@aboucaud feel free to push directly to the branch if you go over the notebook

**Comment by aboucaud** [comment]
> @aboucaud feel free to push directly to the branch if you go over the notebook

I don't really feel comfortable working on the same notebook :)
Have already screwed a few times when merging, depending on my local config.

**Comment by jorisvandenbossche** [comment]
I won't work on it the coming time

**Comment by jorisvandenbossche** [comment]
Merging, that will make it easier to further do fixes

**Pull request merged**
